config/routes.rb
Rails.application.routes.draw do
	# get '/' => 'linked_url#index'
	# get '/new' => 'linked_url#new'

resources :linked_url

#           Prefix Verb   URI Pattern                    Controller#Action
# linked_url_index GET    /linked_url(.:format)          linked_url#index
#                  POST   /linked_url(.:format)          linked_url#create
#   new_linked_url GET    /linked_url/new(.:format)      linked_url#new
#  edit_linked_url GET    /linked_url/:id/edit(.:format) linked_url#edit
#       linked_url GET    /linked_url/:id(.:format)      linked_url#show
#                  PATCH  /linked_url/:id(.:format)      linked_url#update
#                  PUT    /linked_url/:id(.:format)      linked_url#update
#                  DELETE /linked_url/:id(.:format)      linked_url#destroy

end

app/models/linked_url.rb
class LinkedUrl < ActiveRecord::Base
	validates :long_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/linked_url_controller.rb
class LinkedUrlController < ApplicationController
	def index
	end

	def new
		@linkedurl = LinkedUrl.new
	end

	def create
		@linkedurl = LikedUrl.new linkedurl_params
		
		if @linkedurl.save
			redirect_to action: 'index'
		else
			render 'new'
		end
	end

	private
	def linkedurl_params
		params.rquire(:linkedurl).permit(:long_url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/linked_url_helper.rb
module LinkedUrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>URLParser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/linked_url/index.html.erb
<h2> Arale roolz </h2>
<h3> Press <%= link_to("here", new_linked_url_path) %> to Short an URL </h3>

app/views/linked_url/new.html.erb
<%= form_for [@linkedurl] do |f| %>
	<%= f.label :long_url %>
	<%= f.text_field :long_url %>
	<br>
	<%= f.submit 'Save' %>
<% end %>